import type { Metadata } from "next";
import { site } from "./site";

/** Social share image, generated by app/og.png/route.tsx. */
export const ogImage = {
  url: "/og.png",
  width: 1200,
  height: 630,
  type: "image/png",
  alt: `${site.name}, general contractor in ${site.city}, ${site.state}`,
};

/**
 * Per-page metadata: title, description, canonical URL, and matching Open Graph and
 * Twitter tags. Next replaces (not merges) a parent's `openGraph`, so each page sets it in full.
 * `path` should end in "/" to match the exported URLs (`trailingSlash: true`).
 */
export function pageMetadata({
  path,
  title,
  description,
}: {
  path: string;
  title: string;
  description: string;
}): Metadata {
  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type: "website",
      siteName: site.name,
      locale: "en_US",
      url: path,
      title,
      description,
      images: [ogImage],
    },
    twitter: { card: "summary_large_image", title, description, images: [ogImage] },
  };
}

/** Service area for JSON-LD: the state, the home county, and the cities listed on the home page. */
export const areaServedJsonLd = [
  { "@type": "State", name: site.serviceArea },
  { "@type": "AdministrativeArea", name: `${site.county}, UT` },
  ...site.serviceCities.map((city) => ({ "@type": "City", name: `${city}, UT` })),
];

/** Stable identifier for the business node, so other JSON-LD on the site can reference it. */
export const businessId = `${site.url}/#business`;

/** Renders schema.org structured data as a JSON-LD script tag. */
export function JsonLd({ data }: { data: object }) {
  return (
    <script
      type="application/ld+json"
      // Escape "<" so content can never close the script tag early.
      dangerouslySetInnerHTML={{ __html: JSON.stringify(data).replace(/</g, "\\u003c") }}
    />
  );
}
